#to get 14.04:
#sudo: required
#dist: trusty

language: python
python:
  - "3.5.1"
  - "3.5"
  - "3.6.0b4"
  - "3.6-dev"
  - "nightly"

install: "pip install -r requirements.txt"

script:
  (cd cocrawler; make test_coverage)
after_success:
  (cd cocrawler; coveralls)
