language: python
python:
  - "3.5.0"
  - "3.5.1"
  - "3.5.2"
  - "3.5"
#  - "3.6-dev" # also broken for a while
#  - "nightly" # broken for several nights in a row

install: "pip install -r requirements.txt"

script:
  (cd cocrawler; make test_coverage)
after_success:
  (cd cocrawler; coveralls)
